### ISSUE TITLE
order problem

### ISSUE THREAD

**Issue by shmilyoo** [caesar0301/treelib#53]
now children display order is not according to the insert order but the node.tag order . 
is there any way to change the order parameter?

**Comment by caesar0301** [comment]
This is possible, but it needs some modification to Node class and related functions. As suggested by @aronadaal in 83d64f7dae374c34f2ff43bae98eed579a61eaec, we use Dict to store node list for efficiency. The modification can be as following: 1) add an order var. to Node class to record the global insertion time, e.g., an increasing ID. 2) use this inner var. to sort children wherever they are returned.

I am not sure I will have time to add this feature and give sufficient tests of the library, because I have an urgent deadline for my phd dissertation in the coming month. If your needs are urgent, you can implement this feature freely and give me a PR. I appreciate that very much.

Xiaming

**Comment by caesar0301** [comment]
#60 Thansk Daniel!
